# Numpy Datatypes

In [19]:
import numpy as np

In [30]:
# One Dimensional
a1=np.array([1,2,3,4])

In [31]:
type(a1)

numpy.ndarray

In [32]:
# Two Dimensional
a2=np.array([[1,2,3],[4,5,6]])

In [33]:
# Three Dimensional
a3=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
            [[10,11,12],
             [14,15,16],
             [17,18,19]]])

In [34]:
a1,a2,a3

(array([1, 2, 3, 4]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [14, 15, 16],
         [17, 18, 19]]]))

In [35]:
a2.shape

(2, 3)

In [36]:
a3.shape

(2, 3, 3)

In [37]:
a1.ndim

1

In [38]:
a2.ndim

2

In [39]:
a3.ndim

3