# Creating Numpy Arrays

In [1]:
import numpy as np

In [2]:
# One-dimensional
a1=np.array([1,2,3,4])

In [3]:
# Two-Dimensional
a2=np.array([[1.0,2,3],[4,5,6]])

In [4]:
# Three-Dimensional
a3=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
            [[10,11,12],
             [14,15,16],
             [17,18,19]]])

In [5]:
a3.size

18

In [6]:
a1.dtype

dtype('int64')

In [7]:
a2.dtype 

dtype('float64')

In [8]:
# Creates a NumPy array filled with 1s
ones=np.ones((4,6,2))

In [9]:
ones

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [10]:
ones.dtype

dtype('float64')

In [24]:
# Creates a NumPy array filled with 0s
zero=np.zeros((2,3))

In [25]:
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# Creates an array with evenly spaced values
ranges=np.arange(0,20,2)

In [27]:
ranges

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
# Creates an array of random integers
random_array = np.random.randint(0,30,size=(5,5))

In [29]:
random_array

array([[ 4, 21, 25, 14, 23],
       [15, 29, 18,  5, 11],
       [ 0, 21, 21,  2, 28],
       [11, 10, 25,  3,  5],
       [13,  6, 26,  3, 11]], dtype=int32)

In [36]:
# Creates an array of random decimal (floating-point) numbers between 0.0 and 1.0
random_array2 = np.random.random((6,5))

In [37]:
random_array2

array([[0.98034929, 0.4043399 , 0.18787864, 0.88061473, 0.38664357],
       [0.16759427, 0.34134696, 0.32182158, 0.51418378, 0.47868154],
       [0.41127336, 0.81962148, 0.60320514, 0.90718517, 0.51287949],
       [0.6795643 , 0.00687958, 0.93564463, 0.22221445, 0.1948736 ],
       [0.62430591, 0.41996429, 0.0120356 , 0.04913454, 0.4477436 ],
       [0.97163671, 0.69854686, 0.92425491, 0.09544906, 0.7499202 ]])

In [38]:
# Creates an array of random decimal (floating-point) numbers between 0.0 and 1.0
random_array3 = np.random.rand(6,5)

In [39]:
random_array3

array([[0.57863675, 0.67667502, 0.60867548, 0.46383532, 0.43986115],
       [0.80222712, 0.86011036, 0.68726161, 0.42583749, 0.56913636],
       [0.44476221, 0.83697055, 0.31513925, 0.81510965, 0.06995527],
       [0.81256065, 0.91913543, 0.74813233, 0.78361636, 0.97276527],
       [0.16598824, 0.05221471, 0.75437595, 0.27189326, 0.83382387],
       [0.67352257, 0.19875346, 0.97042472, 0.22483279, 0.18245356]])

# Numpy Random seed

In [85]:
np.random.seed(7)
random_array4 =np.random.random((10,5))
random_array4

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518, 0.97798951],
       [0.53849587, 0.50112046, 0.07205113, 0.26843898, 0.4998825 ],
       [0.67923   , 0.80373904, 0.38094113, 0.06593635, 0.2881456 ],
       [0.90959353, 0.21338535, 0.45212396, 0.93120602, 0.02489923],
       [0.60054892, 0.9501295 , 0.23030288, 0.54848992, 0.90912837],
       [0.13316945, 0.52341258, 0.75040986, 0.66901324, 0.46775286],
       [0.20484909, 0.49076589, 0.37238469, 0.47740115, 0.36589039],
       [0.83791799, 0.76864751, 0.31399468, 0.57262533, 0.27604905],
       [0.45284293, 0.35297837, 0.65739946, 0.37035108, 0.45909298],
       [0.71932412, 0.41299183, 0.90642327, 0.18045162, 0.74111887]])

In [86]:
np.random.seed(8)
random_array5 = np.random.randint(0,25,size=(2,5,6))
random_array5

array([[[ 3, 20, 17,  9,  5,  8],
        [19,  8, 16, 13, 21, 17],
        [19, 10, 12, 13,  9, 15],
        [ 2, 18, 14,  6, 24,  9],
        [19,  4, 21, 21,  7, 10]],

       [[ 9,  2,  6,  9,  5, 14],
        [17, 11, 15, 11, 22, 20],
        [13, 21,  8, 15, 10,  0],
        [ 7, 13,  2,  6,  7,  4],
        [24,  6,  4,  5, 11,  2]]], dtype=int32)