# Numpy unique

In [7]:
import numpy as np

In [8]:
np.random.seed(8)
random_array = np.random.randint(0,25,size=(2,5,6))
random_array

array([[[ 3, 20, 17,  9,  5,  8],
        [19,  8, 16, 13, 21, 17],
        [19, 10, 12, 13,  9, 15],
        [ 2, 18, 14,  6, 24,  9],
        [19,  4, 21, 21,  7, 10]],

       [[ 9,  2,  6,  9,  5, 14],
        [17, 11, 15, 11, 22, 20],
        [13, 21,  8, 15, 10,  0],
        [ 7, 13,  2,  6,  7,  4],
        [24,  6,  4,  5, 11,  2]]], dtype=int32)

In [9]:
np.unique(random_array)

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 24], dtype=int32)

# Viewing Arrays

In [14]:
a1=np.array([1,2,3,4])

In [15]:
a2=np.array([[1,2,3],[4,5,6]])

In [16]:
a3=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
            [[10,11,12],
             [14,15,16],
             [17,18,19]]])

In [26]:
a1[2]

np.int64(3)

In [27]:
a2[0,1]

np.int64(2)

In [28]:
a2[0][1] 

np.int64(2)

In [25]:
a3[0,1,1]

np.int64(5)

In [34]:
a1[0:2]

array([1, 2])

In [37]:
a2[1,:2]

array([4, 5])

In [41]:
a3[0:2,0:3:2,:2]

array([[[ 1,  2],
        [ 7,  8]],

       [[10, 11],
        [17, 18]]])

In [44]:
# A view shares the same memory as the original array
arr = np.array([1,2,3,4])
view = arr.view()
view[0] = 100
print(arr)

[100   2   3   4]


In [45]:
# A copy creates a completely separate array
arr = np.array([1,2,3,4])
copy = arr.copy()
copy[0] = 100
print(arr)

[1 2 3 4]
