# Manipulation and Comparision of Arrays ( Arithmetic )

In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3])

In [3]:
a2=np.array([[1,2,3],[4,5,6]])

In [4]:
a3=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
            [[10,11,12],
             [14,15,16],
             [17,18,19]]])

In [5]:
ones=np.ones(3)

In [6]:
# Array Addition
a1+ones
np.add(a1,a2)

array([[2, 4, 6],
       [5, 7, 9]])

In [7]:
# Array Subtraction
a1-ones

array([0., 1., 2.])

In [8]:
a1*ones

array([1., 2., 3.])

In [9]:
a1*a1

array([1, 4, 9])

In [10]:
# Array Division
ones/a1

array([1.        , 0.5       , 0.33333333])

In [11]:
# Floor Division
ones//a1

array([1., 0., 0.])

In [12]:
# Exponential
a1**3

array([ 1,  8, 27])

In [13]:
# Modulus
a2%a1
np.mod(a1,ones)

array([0., 0., 0.])

In [14]:
# Squaring
np.square(a1)

array([1, 4, 9])

In [15]:
# Squareroot
np.sqrt(

_IncompleteInputError: incomplete input (2615385148.py, line 2)

# Manipulation and Comparision of Arrays ( Aggregate )

In [ ]:
li_1=[1,2,3]
li_1

In [ ]:
sum(li_1)

In [ ]:
np.sum(li_1)

###### Use Python functions on Python datatpes and Numpy Functions on Numpy datatypes

In [ ]:
# Creating huge array
massive_arr = np.random.random(100000)

In [ ]:
massive_arr[:100]

In [ ]:
%timeit sum(massive_arr)  # Normal Python sum
%timeit np.sum(massive_arr)  # Numpy sum

In [ ]:
# Mean value
np.mean(a2)

In [ ]:
# Maximum value
np.max(a2)

In [ ]:
# Minimun value
np.min(massive_arr)

In [ ]:
# Standard Deviation
np.std(a2)

In [ ]:
# Variance 
np.var(a2)