# Reshape and Transpose

In [2]:
import numpy as np

In [3]:
a2=np.array([[1,2,3],[4,5,6]])

In [4]:
a3=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
            [[10,11,12],
             [14,15,16],
             [17,18,19]]])

In [24]:
# This will throw an error because of the shape of a2 and a3
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [25]:
a2.shape , a3.shape

((2, 3), (2, 3, 3))

##### Reshape

In [26]:
a2_reshape = a2.reshape(2,3,1)           

In [27]:
a2_reshape.shape

(2, 3, 1)

In [28]:
a2_reshape

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [29]:
a2_reshape*a3

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 21,  24,  27]],

       [[ 40,  44,  48],
        [ 70,  75,  80],
        [102, 108, 114]]])

##### Transpose

In [30]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [31]:
a2.shape , a2.T.shape

((2, 3), (3, 2))

In [32]:
a3.T

array([[[ 1, 10],
        [ 4, 14],
        [ 7, 17]],

       [[ 2, 11],
        [ 5, 15],
        [ 8, 18]],

       [[ 3, 12],
        [ 6, 16],
        [ 9, 19]]])

In [33]:
a3.shape , a3.T.shape

((2, 3, 3), (3, 3, 2))