# Dot Product

In [2]:
import numpy as np

In [3]:
a1=np.array([1,2,3])

In [4]:
a2=np.array([[1,2,3],[4,5,6]])

In [8]:
a3=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
            [[10,11,12],
             [14,15,16],
             [17,18,19]]])

In [9]:
# This is Hadamard product
a1*a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [31]:
np.random.seed(5)
matrix_1 = np.random.randint(0,10,size=(5,3))

In [32]:
np.random.seed(6)
matrix_2 = np.random.randint(10,size=(5,3))

In [33]:
matrix_1 , matrix_2

(array([[3, 6, 6],
        [0, 9, 8],
        [4, 7, 0],
        [0, 7, 1],
        [5, 7, 0]], dtype=int32),
 array([[9, 3, 4],
        [0, 9, 1],
        [9, 1, 4],
        [1, 8, 2],
        [4, 2, 5]], dtype=int32))

In [34]:
matrix_1*matrix_2

array([[27, 18, 24],
       [ 0, 81,  8],
       [36,  7,  0],
       [ 0, 56,  2],
       [20, 14,  0]], dtype=int32)

In [40]:
# This is a Dot product, but it will throw an error
np.dot(matrix_1,matrix_2)

In [39]:
matrix_1.shape , matrix_2.T.shape

((5, 3), (3, 5))

In [36]:
matrix_3 = np.dot(matrix_1,martix_2.T)

In [38]:
matrix_3 , matrix_3.shape

(array([[114,  60, 105,  84,  99],
        [126,  89, 118, 118, 121],
        [ 74,  63,  70,  42,  83],
        [ 51,  64,  50,  50,  68],
        [ 82,  63,  77,  42,  88]], dtype=int32),
 (5, 5))