# Comparison operator

In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3])

In [3]:
a2=np.array([[1,2,3],[4,5,6]])

In [4]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [5]:
a1>=a2

array([[ True,  True,  True],
       [False, False, False]])

In [6]:
a1<a2

array([[False, False, False],
       [ True,  True,  True]])

In [7]:
a1<=a2

array([[ True,  True,  True],
       [ True,  True,  True]])

In [8]:
a1==a2

array([[ True,  True,  True],
       [False, False, False]])

In [9]:
a1!=a2

array([[False, False, False],
       [ True,  True,  True]])

In [10]:
bool_array = a1!=a2

In [11]:
bool_array

array([[False, False, False],
       [ True,  True,  True]])

In [12]:
a1==2

array([False,  True, False])

# Sorting Arrays

In [20]:
np.random.seed(3)
random_array = np.random.randint(10,size=(5,5))

In [21]:
random_array

array([[8, 9, 3, 8, 8],
       [0, 5, 3, 9, 9],
       [5, 7, 6, 0, 4],
       [7, 8, 1, 6, 2],
       [2, 1, 3, 5, 8]], dtype=int32)

In [22]:
np.sort(random_array)

array([[3, 8, 8, 8, 9],
       [0, 3, 5, 9, 9],
       [0, 4, 5, 6, 7],
       [1, 2, 6, 7, 8],
       [1, 2, 3, 5, 8]], dtype=int32)

In [25]:
# Returns the indices that would sort each column of the array in ascending order
np.argsort(random_array,axis=0)

array([[1, 4, 3, 2, 3],
       [4, 1, 0, 4, 2],
       [2, 2, 1, 3, 0],
       [3, 3, 4, 0, 4],
       [0, 0, 2, 1, 1]])

In [24]:
# Finds the index of the maximum value row-wise
np.argmax(random_array,axis=1)

array([1, 3, 1, 1, 4])

##### Note : axis = 0  → Columns ↓
#####        axis = 1  → Rows →